apiVersion: v1
kind: Namespace
metadata:
  name: api-service
  labels:
    name: api-service
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-service
  labels:
    name: auth-service
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: image-service
  labels:
    name: image-service
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring